apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  labels:
    app: nodejs
spec:
  ports:
  - port: {{ .Values.serviceport }}
    targetPort: {{ .Values.nodejsport }}
  selector:
    app: nodejs

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nodejs
spec:
  rules:
  - host: {{ .Values.domain_name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs-svc
          servicePort: {{ .Values.serviceport }}
