apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
   app: mongodb
spec:
 ports:
 - port: {{ .Values.mongo_port }}
   targetPort: {{ .Values.mongo_port }}
 clusterIP: None
 selector:
   role: mongo
